<template>
  <div>
    <ds-section
      secondary
      fullheight
      centered>
      <ds-space>
        <ds-logo inverse/>
      </ds-space>
      <ds-heading>Vue Design System<br>Boilerplate</ds-heading>
      <ds-space margin-bottom="xxx-large">
        <ds-button
          path="https://cion.visualjerk.de"
          icon="desktop">Styleguide Demo</ds-button>
        <ds-button
          path="https://github.com/visualjerk/vue-cion-design-system"
          icon="github">GitHub</ds-button>
      </ds-space>
      <ds-space>
        <ds-flex 
          :gutter="{ base: 'base', lg: 'xx-large' }"
          :width="{ base: '100%', md: 1 }">
          <ds-flex-item>
            <ds-card
              primary
              centered>
              <ds-heading
                slot="header"
                tag="h3">
                <ds-icon name="book"/><br><br>
                Living<br>Styleguide
              </ds-heading>
              See the styleguide adapt to your design system as you move forward.
            </ds-card>
          </ds-flex-item>
          <ds-flex-item>
            <ds-card
              primary
              centered>
              <ds-heading
                slot="header"
                tag="h3">
                <ds-icon name="file-code"/><br><br>
                Component<br>Documentation
              </ds-heading>
              Autogenerated documentation for your components with integrated playground.
            </ds-card>
          </ds-flex-item>
          <ds-flex-item>
            <ds-card
              primary
              centered>
              <ds-heading
                slot="header"
                tag="h3">
                <ds-icon name="cubes"/><br><br>
                Basic<br>Components
              </ds-heading>
              Includes lots of basic components to help you move faster.
            </ds-card>
          </ds-flex-item>
        </ds-flex>
      </ds-space>
    </ds-section>
  </div>
</template>

<script>
export default {
  data() {
    return {
      routes: [
        { name: 'Introduction' },
        {
          name: 'Layout',
          children: [
            { name: 'Container' },
            { name: 'Page' },
            { name: 'Page Title' }
          ]
        },
        { name: 'Typography' },
        { name: 'Navigation' }
      ]
    }
  }
}
</script>
