<template>
  <div>
    <ds-section
      secondary
      fullheight
      centered>
      <ds-space>
        <ds-logo inverse/>
      </ds-space>
      <ds-heading>Vue Design System<br>Boilerplate</ds-heading>
      <ds-space margin-bottom="xxx-large">
        <ds-button
          path="https://cion.visualjerk.de"
          icon="desktop">Styleguide Demo</ds-button>&nbsp;
        <ds-button
          path="https://github.com/visualjerk/vue-cion-design-system"
          icon="github">GitHub</ds-button>
      </ds-space>
      <ds-space>
        <ds-flex
          :gutter="{ base: 'base', lg: 'xx-large' }"
          :width="{ base: '100%', md: 1 }">
          <ds-flex-item>
            <ds-card
              icon="book"
              primary
              centered
              hover>
              <ds-heading
                slot="header"
                tag="h3">
                Living<br>Styleguide
              </ds-heading>
              See the styleguide adapt to your design system as you move forward.
            </ds-card>
          </ds-flex-item>
          <ds-flex-item>
            <ds-card
              icon="file-code"
              primary
              centered
              hover>
              <ds-heading
                slot="header"
                tag="h3">
                Component<br>Documentation
              </ds-heading>
              Autogenerated documentation for your components with integrated playground.
            </ds-card>
          </ds-flex-item>
          <ds-flex-item>
            <ds-card
              icon="cubes"
              primary
              centered
              hover>
              <ds-heading
                slot="header"
                tag="h3">
                Basic<br>Components
              </ds-heading>
              Includes lots of basic components to help you move faster.
            </ds-card>
          </ds-flex-item>
        </ds-flex>
      </ds-space>
    </ds-section>
    <ds-section>
      <ds-heading 
        tag="h2" 
        size="h1">First steps</ds-heading>
      <ds-space>
        <ds-list
          size="large"
          ordered>
          <ds-list-item>
            Download the boilerplate<br>
            <pre>git clone https://github.com/visualjerk/vue-cion-design-system.git your-system-name</pre>
          </ds-list-item>
          <ds-list-item>
            Install the dependencies<br>
            <pre>cd your-system-name && yarn install</pre>
          </ds-list-item>
          <ds-list-item>
            Start development server<br>
            <pre>yarn dev</pre>
          </ds-list-item>
        </ds-list>
      </ds-space>
      <ds-space>
        <ds-flex
          :gutter="{ base: 'base', lg: 'xx-large' }"
          :width="{ base: '100%', md: 1 }">
          <ds-flex-item>
            <ds-card
              icon="book"
              centered
              hover>
              <ds-heading
                slot="header"
                tag="h3">
                Living<br>Styleguide
              </ds-heading>
              See the styleguide adapt to your design system as you move forward.
            </ds-card>
          </ds-flex-item>
          <ds-flex-item>
            <ds-card
              icon="file-code"
              centered
              hover>
              <ds-heading
                slot="header"
                tag="h3">
                Component<br>Documentation
              </ds-heading>
              Autogenerated documentation for your components with integrated playground.
            </ds-card>
          </ds-flex-item>
          <ds-flex-item>
            <ds-card
              icon="cubes"
              centered
              hover>
              <ds-heading
                slot="header"
                tag="h3">
                Basic<br>Components
              </ds-heading>
              Includes lots of basic components to help you move faster.
            </ds-card>
          </ds-flex-item>
        </ds-flex>
      </ds-space>
    </ds-section>
  </div>
</template>

<script>
export default {
  data() {
    return {
      routes: [
        { name: 'Introduction' },
        {
          name: 'Layout',
          children: [
            { name: 'Container' },
            { name: 'Page' },
            { name: 'Page Title' }
          ]
        },
        { name: 'Typography' },
        { name: 'Navigation' }
      ]
    }
  }
}
</script>
